name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    if: github.repository == '84codes/rubocop-eightyfourcodes'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for trusted publishing
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
      # ensure gem can be built and installed, push to rubygems.org
      - run: gem build rubocop-eightyfourcodes
      - run: gem install *.gem
      - run: |
          ruby -S gem exec sigstore-cli:0.2.2 sign *.gem --bundle attestation.sigstore.json
      - run: |
          gem push --attestation attestation.sigstore.json *.gem
